name: Deploy Leantime & Gatus

env:
  AWS_REGION: us-east-1

on:
  push:
    branches:
      - main

jobs:
  Deploy-Leantime:
    name: Deploy Leantime App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: leantime/task-definition.json
          service: leantime-service
          cluster: lks-oss-cluster
          wait-for-service-stability: true

  Deploy-Gatus:
    name: Deploy Gatus App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # check 
      - name: Check config.yaml
        run: cat gatus/config/config.yaml
      - name: Check Directory
        run: ls gatus/config

      - name: Deploy Gatus Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: gatus/task-definition.json
          service: gatus-service
          cluster: lks-oss-cluster-1
          wait-for-service-stability: true